pipelines:
  default:
    - step:
     script:
        - pipe: atlassian/heroku-deploy:1.1.4
          variables:
            HEROKU_API_KEY: $HEROKU_API_KEY
            HEROKU_APP_NAME: $HEROKU_APP_NAME
            ZIP_FILE: $HEROKU_APP_ZIP_NAME